# Generated by Django 5.1.2 on 2026-03-28 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PilatesClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "arms",
                    models.IntegerField(
                        choices=[
                            (1, "Easy"),
                            (2, "Medium"),
                            (3, "Hard"),
                            (4, "Death 💀"),
                        ]
                    ),
                ),
                (
                    "legs",
                    models.IntegerField(
                        choices=[
                            (1, "Easy"),
                            (2, "Medium"),
                            (3, "Hard"),
                            (4, "Death 💀"),
                        ]
                    ),
                ),
                (
                    "abs",
                    models.IntegerField(
                        choices=[
                            (1, "Easy"),
                            (2, "Medium"),
                            (3, "Hard"),
                            (4, "Death 💀"),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classes.instructor",
                    ),
                ),
            ],
        ),
    ]
