# Generated by Django 5.1.2 on 2026-04-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pilatesclass",
            name="calories",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pilatesclass",
            name="obliques",
            field=models.IntegerField(
                choices=[(1, "Easy"), (2, "Medium"), (3, "Hard"), (4, "Death 💀")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="pilatesclass",
            name="abs",
            field=models.IntegerField(
                choices=[(1, "Easy"), (2, "Medium"), (3, "Hard"), (4, "Death 💀")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="pilatesclass",
            name="arms",
            field=models.IntegerField(
                choices=[(1, "Easy"), (2, "Medium"), (3, "Hard"), (4, "Death 💀")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="pilatesclass",
            name="legs",
            field=models.IntegerField(
                choices=[(1, "Easy"), (2, "Medium"), (3, "Hard"), (4, "Death 💀")],
                default=0,
            ),
        ),
    ]
